<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<main style="max-width:760px; padding:40px 24px;">
  <img src="/images/brand/adwitix-logo-full.jpg" alt="AdwitiX" style="width:230px; max-width:100%;">

  <h1 style="font-size:22px; margin-top:18px;">Chronicle Verification</h1>
  <p style="font-size:12px; color:var(--ink-3);">This page requires no login; it's reachable only with the exact token from the QR code or verification link on the certified PDF.</p>

  <p style="font-size:13px; margin-top:14px;">This AX Certified Proceedings has been automatically generated by the ADWITIX Platform based on the information, activities, approvals and records captured during the lifecycle of the event. It presents a structured summary of the proceedings together with the associated commercial outcome, compliance status and supporting records. The report forms part of the official digital record maintained for this event.</p>

  <?php if ($hashMatches): ?>
    <p style="color:var(--emerald-deep); font-size:13px; background:var(--emerald-soft); padding:12px; border-radius:8px; margin-top:16px;">✓ Digital Verification: this record's content hash matches what was certified at generation. Not altered.</p>
  <?php else: ?>
    <p style="color:#B5482F; font-size:13px; background:#FBE8E4; padding:12px; border-radius:8px; margin-top:16px;">⚠ Digital Verification FAILED: this record's content does not match its certified hash.</p>
  <?php endif; ?>

  <table style="width:100%; border-collapse:collapse; margin-top:20px; font-size:13px;">
    <tr><td style="padding:6px 0; color:var(--ink-3);">Reference Number</td><td style="padding:6px 0; font-weight:700;"><?= esc($chronicle['reference_number']) ?></td></tr>
    <tr><td style="padding:6px 0; color:var(--ink-3);">Certified</td><td style="padding:6px 0;"><?= esc(substr($chronicle['generated_at'], 0, 16)) ?> UTC</td></tr>
    <tr><td style="padding:6px 0; color:var(--ink-3);">Version</td><td style="padding:6px 0;"><?= esc($chronicle['version']) ?></td></tr>
    <tr><td style="padding:6px 0; color:var(--ink-3);">Trading Session</td><td style="padding:6px 0;"><?= esc($reportData['saleEvent']['ern']) ?></td></tr>
    <tr><td style="padding:6px 0; color:var(--ink-3);">Trading Format</td><td style="padding:6px 0;"><?= esc(sale_format_label($reportData['saleEvent']['saleFormat'])) ?></td></tr>
  </table>

  <p style="margin-top:20px;"><a href="/chronicle/verify/<?= esc($chronicle['verification_token']) ?>/pdf" class="btn btn-emerald">Download Certified PDF</a></p>

  <h3 style="font-size:15px; margin-top:28px;">Supporting Evidence</h3>
  <?php if (empty($media)): ?>
    <p style="font-size:12px; color:var(--ink-3);">No photographs or documents attached to this Lot.</p>
  <?php else: ?>
    <?php foreach ($media as $m): ?>
      <p style="font-size:12px; padding:6px 0; border-bottom:1px solid var(--line);">
        <a href="/<?= esc($m['file_path']) ?>" target="_blank"><?= esc($m['original_filename'] ?: $m['file_path']) ?></a><?= $m['is_primary'] ? ' (primary)' : '' ?>
      </p>
    <?php endforeach; ?>
  <?php endif; ?>

  <h3 style="font-size:15px; margin-top:28px;">Audit-Trail Excerpt</h3>
  <?php if (empty($reportData['timeline'])): ?>
    <p style="font-size:12px; color:var(--ink-3);">No timeline entries recorded.</p>
  <?php else: ?>
    <?php foreach ($reportData['timeline'] as $event): ?>
      <p style="font-size:12px; padding:6px 0; border-bottom:1px solid var(--line);"><?= esc(substr($event['occurredAt'], 0, 19)) ?> UTC — <?= esc($event['eventType']) ?></p>
    <?php endforeach; ?>
  <?php endif; ?>

  <p style="font-size:11px; color:var(--ink-3); margin-top:20px;">Chain reference: <?= esc(substr($reportData['auditChainRecordHash'] ?? '', 0, 16)) ?>&hellip; — cross-checkable against the platform's own digital repository.</p>

  <h3 style="font-size:15px; margin-top:28px;">Record Integrity Statement</h3>
  <p style="font-size:12px; color:var(--ink-3);">This report represents a factual summary of the recorded proceedings and does not alter, replace or supersede the underlying digital records. The complete chronology of events, supporting documents, media, approvals and transaction history continue to remain available within the authorised digital repository for verification, audit and future reference in accordance with applicable organisational policies and data retention requirements.</p>

  <h3 style="font-size:15px; margin-top:20px;">Closing Statement &amp; Disclaimer</h3>
  <p style="font-size:12px; color:var(--ink-3);">This report has been generated from information available within the ADWITIX Platform as on the date and time of certification. It is intended to facilitate operational review, management reporting and institutional record keeping. The report should be read together with the underlying digital records wherever detailed verification or evidentiary reference is required. Any subsequent activity or authorised update after the time of generation shall form part of a later version of the proceedings.</p>

  <p style="font-size:11px; color:var(--ink-3); margin-top:24px; padding-top:14px; border-top:1px solid var(--line);">www.AdwitiX.com</p>
</main>
<?= $this->endSection() ?>
